version: "3.8"
services:
  videoroom_advanced:
    image: membraneframework/demo_webrtc_videoroom_advanced:latest
    secrets:
      - turn_servers
    environment:
      VIRTUAL_HOST: "demo-webrtc-videoroom-advanced.membraneframework.org"
      LETSENCRYPT_HOST: "demo-webrtc-videoroom-advanced.membraneframework.org"
      STUN_SERVERS: "stun.l.google.com:19302"
      TURN_SETTINGS: "127.0.0.1:abc"


  nginx-proxy:
    image: jwilder/nginx-proxy:0.8.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0.2
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: admin+demo@membraneframework.org

secrets:
  turn_servers:
    external: true
    
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-data:
  
