version: "3.8"
services:
  videoroom_advanced:
    image: membraneframework/demo_webrtc_videoroom_advanced:latest
    environment:
      VIRTUAL_HOST: "videoroom.membraneframework.org"
      LETSENCRYPT_HOST: "videoroom.membraneframework.org"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "95.217.133.165"
      INTEGRATED_TURN_PORT_RANGE: "50000-50100"
      INTEGRATED_TCP_TURN_PORT: "50100"
    ports: 
      - "50000-50100:50000-50100/tcp"
      - "50000-50100:50000-50100/udp"

      
  nginx-proxy:
    image: jwilder/nginx-proxy:0.8.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0.2
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: admin+demo@membraneframework.org

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-data:
